// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newUserShare(db *gorm.DB, opts ...gen.DOOption) userShare {
	_userShare := userShare{}

	_userShare.userShareDo.UseDB(db, opts...)
	_userShare.userShareDo.UseModel(&model.UserShare{})

	tableName := _userShare.userShareDo.TableName()
	_userShare.ALL = field.NewAsterisk(tableName)
	_userShare.ID = field.NewInt64(tableName, "id")
	_userShare.UID = field.NewInt64(tableName, "uid")
	_userShare.ResType = field.NewString(tableName, "res_type")
	_userShare.ResID = field.NewInt64(tableName, "res_id")
	_userShare.Res = field.NewString(tableName, "res")
	_userShare.Status = field.NewInt64(tableName, "status")
	_userShare.ViewCount = field.NewInt64(tableName, "view_count")
	_userShare.LastViewedAt = field.NewTime(tableName, "last_viewed_at")
	_userShare.ExpiresAt = field.NewTime(tableName, "expires_at")
	_userShare.Password = field.NewString(tableName, "password")
	_userShare.ShortLink = field.NewString(tableName, "short_link")
	_userShare.CreatedAt = field.NewField(tableName, "created_at")
	_userShare.UpdatedAt = field.NewField(tableName, "updated_at")

	_userShare.fillFieldMap()

	return _userShare
}

type userShare struct {
	userShareDo userShareDo

	ALL          field.Asterisk
	ID           field.Int64
	UID          field.Int64
	ResType      field.String
	ResID        field.Int64
	Res          field.String
	Status       field.Int64
	ViewCount    field.Int64
	LastViewedAt field.Time
	ExpiresAt    field.Time
	Password     field.String
	ShortLink    field.String
	CreatedAt    field.Field
	UpdatedAt    field.Field

	fieldMap map[string]field.Expr
}

func (u userShare) Table(newTableName string) *userShare {
	u.userShareDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userShare) As(alias string) *userShare {
	u.userShareDo.DO = *(u.userShareDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userShare) updateTableName(table string) *userShare {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UID = field.NewInt64(table, "uid")
	u.ResType = field.NewString(table, "res_type")
	u.ResID = field.NewInt64(table, "res_id")
	u.Res = field.NewString(table, "res")
	u.Status = field.NewInt64(table, "status")
	u.ViewCount = field.NewInt64(table, "view_count")
	u.LastViewedAt = field.NewTime(table, "last_viewed_at")
	u.ExpiresAt = field.NewTime(table, "expires_at")
	u.Password = field.NewString(table, "password")
	u.ShortLink = field.NewString(table, "short_link")
	u.CreatedAt = field.NewField(table, "created_at")
	u.UpdatedAt = field.NewField(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userShare) WithContext(ctx context.Context) IUserShareDo {
	return u.userShareDo.WithContext(ctx)
}

func (u userShare) TableName() string { return u.userShareDo.TableName() }

func (u userShare) Alias() string { return u.userShareDo.Alias() }

func (u userShare) Columns(cols ...field.Expr) gen.Columns { return u.userShareDo.Columns(cols...) }

func (u *userShare) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userShare) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 13)
	u.fieldMap["id"] = u.ID
	u.fieldMap["uid"] = u.UID
	u.fieldMap["res_type"] = u.ResType
	u.fieldMap["res_id"] = u.ResID
	u.fieldMap["res"] = u.Res
	u.fieldMap["status"] = u.Status
	u.fieldMap["view_count"] = u.ViewCount
	u.fieldMap["last_viewed_at"] = u.LastViewedAt
	u.fieldMap["expires_at"] = u.ExpiresAt
	u.fieldMap["password"] = u.Password
	u.fieldMap["short_link"] = u.ShortLink
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userShare) clone(db *gorm.DB) userShare {
	u.userShareDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userShare) replaceDB(db *gorm.DB) userShare {
	u.userShareDo.ReplaceDB(db)
	return u
}

type userShareDo struct{ gen.DO }

type IUserShareDo interface {
	gen.SubQuery
	Debug() IUserShareDo
	WithContext(ctx context.Context) IUserShareDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserShareDo
	WriteDB() IUserShareDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserShareDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserShareDo
	Not(conds ...gen.Condition) IUserShareDo
	Or(conds ...gen.Condition) IUserShareDo
	Select(conds ...field.Expr) IUserShareDo
	Where(conds ...gen.Condition) IUserShareDo
	Order(conds ...field.Expr) IUserShareDo
	Distinct(cols ...field.Expr) IUserShareDo
	Omit(cols ...field.Expr) IUserShareDo
	Join(table schema.Tabler, on ...field.Expr) IUserShareDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserShareDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserShareDo
	Group(cols ...field.Expr) IUserShareDo
	Having(conds ...gen.Condition) IUserShareDo
	Limit(limit int) IUserShareDo
	Offset(offset int) IUserShareDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserShareDo
	Unscoped() IUserShareDo
	Create(values ...*model.UserShare) error
	CreateInBatches(values []*model.UserShare, batchSize int) error
	Save(values ...*model.UserShare) error
	First() (*model.UserShare, error)
	Take() (*model.UserShare, error)
	Last() (*model.UserShare, error)
	Find() ([]*model.UserShare, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserShare, err error)
	FindInBatches(result *[]*model.UserShare, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserShare) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserShareDo
	Assign(attrs ...field.AssignExpr) IUserShareDo
	Joins(fields ...field.RelationField) IUserShareDo
	Preload(fields ...field.RelationField) IUserShareDo
	FirstOrInit() (*model.UserShare, error)
	FirstOrCreate() (*model.UserShare, error)
	FindByPage(offset int, limit int) (result []*model.UserShare, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserShareDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userShareDo) Debug() IUserShareDo {
	return u.withDO(u.DO.Debug())
}

func (u userShareDo) WithContext(ctx context.Context) IUserShareDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userShareDo) ReadDB() IUserShareDo {
	return u.Clauses(dbresolver.Read)
}

func (u userShareDo) WriteDB() IUserShareDo {
	return u.Clauses(dbresolver.Write)
}

func (u userShareDo) Session(config *gorm.Session) IUserShareDo {
	return u.withDO(u.DO.Session(config))
}

func (u userShareDo) Clauses(conds ...clause.Expression) IUserShareDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userShareDo) Returning(value interface{}, columns ...string) IUserShareDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userShareDo) Not(conds ...gen.Condition) IUserShareDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userShareDo) Or(conds ...gen.Condition) IUserShareDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userShareDo) Select(conds ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userShareDo) Where(conds ...gen.Condition) IUserShareDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userShareDo) Order(conds ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userShareDo) Distinct(cols ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userShareDo) Omit(cols ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userShareDo) Join(table schema.Tabler, on ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userShareDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userShareDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userShareDo) Group(cols ...field.Expr) IUserShareDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userShareDo) Having(conds ...gen.Condition) IUserShareDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userShareDo) Limit(limit int) IUserShareDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userShareDo) Offset(offset int) IUserShareDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userShareDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserShareDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userShareDo) Unscoped() IUserShareDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userShareDo) Create(values ...*model.UserShare) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userShareDo) CreateInBatches(values []*model.UserShare, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userShareDo) Save(values ...*model.UserShare) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userShareDo) First() (*model.UserShare, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShare), nil
	}
}

func (u userShareDo) Take() (*model.UserShare, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShare), nil
	}
}

func (u userShareDo) Last() (*model.UserShare, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShare), nil
	}
}

func (u userShareDo) Find() ([]*model.UserShare, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserShare), err
}

func (u userShareDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserShare, err error) {
	buf := make([]*model.UserShare, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userShareDo) FindInBatches(result *[]*model.UserShare, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userShareDo) Attrs(attrs ...field.AssignExpr) IUserShareDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userShareDo) Assign(attrs ...field.AssignExpr) IUserShareDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userShareDo) Joins(fields ...field.RelationField) IUserShareDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userShareDo) Preload(fields ...field.RelationField) IUserShareDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userShareDo) FirstOrInit() (*model.UserShare, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShare), nil
	}
}

func (u userShareDo) FirstOrCreate() (*model.UserShare, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShare), nil
	}
}

func (u userShareDo) FindByPage(offset int, limit int) (result []*model.UserShare, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userShareDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userShareDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userShareDo) Delete(models ...*model.UserShare) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userShareDo) withDO(do gen.Dao) *userShareDo {
	u.DO = *do.(*gen.DO)
	return u
}
