name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动检查更新
  workflow_dispatch: # 支持手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/haierkeys/fast-note-sync-service.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
